function(addDeps)
  message("${CMAKE_CURRENT_SOURCE_DIR} > node -e \"require('@ccpm/dep-paths').getDepPaths('${CMAKE_CURRENT_SOURCE_DIR}').forEach(p => console.log(p))\"")
  execute_process(COMMAND node -e "require('@ccpm/dep-paths').getDepPaths('${CMAKE_CURRENT_SOURCE_DIR}').forEach(p => console.log(p))"
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE DEPS_LIST
  )
  if(DEPS_LIST)
    string(REPLACE "\n" ";" DEPS_LIST ${DEPS_LIST})
    foreach(pkg ${DEPS_LIST})
      string(REPLACE "," ";" DEP_PATHS ${pkg})
      list(GET DEP_PATHS 0 ABSOLUTE_PATH)
      list(GET DEP_PATHS 1 RELATIVE_PATH)
      get_property(CCPM_SOURCE_LIST GLOBAL PROPERTY "CCPM_SOURCE_LIST")
      if(NOT CCPM_SOURCE_LIST)
        set_property(GLOBAL PROPERTY "CCPM_SOURCE_LIST" "${ABSOLUTE_PATH}")
        message("${CMAKE_CURRENT_SOURCE_DIR} > add_subdirectory(\"${ABSOLUTE_PATH}\" \"${RELATIVE_PATH}\")")
        add_subdirectory(${ABSOLUTE_PATH} ${RELATIVE_PATH})
      else()
        list(FIND CCPM_SOURCE_LIST ${ABSOLUTE_PATH} FIND_INDEX)
        if(${FIND_INDEX} MATCHES "-1")
          set_property(GLOBAL PROPERTY "CCPM_SOURCE_LIST" "${CCPM_SOURCE_LIST};${ABSOLUTE_PATH}")
          message("${CMAKE_CURRENT_SOURCE_DIR} > add_subdirectory(\"${ABSOLUTE_PATH}\" \"${RELATIVE_PATH}\")")
          add_subdirectory(${ABSOLUTE_PATH} ${RELATIVE_PATH})
        else()
          message("${CMAKE_CURRENT_SOURCE_DIR} > found ${ABSOLUTE_PATH}")
        endif()
      endif()
    endforeach()
  endif()
endfunction()

addDeps()
